(()=>{const $=id=>document.getElementById(id);const pending=new Map();let modal=null;let list=null;let summary=null;let autoTimer=null;
function addStyles(){if(document.getElementById("diagStyle"))return;const s=document.createElement("style");s.id="diagStyle";s.textContent=`
.diagModal{position:fixed;inset:0;z-index:80;display:grid;place-items:center;padding:18px;background:#05060bf2;backdrop-filter:blur(22px)}
.diagCard{width:min(900px,100%);max-height:min(820px,94vh);display:flex;flex-direction:column;overflow:hidden;border:1px solid #ffffff16;background:linear-gradient(145deg,#151823,#0c0f17);border-radius:24px;box-shadow:0 35px 110px #000c}
.diagHead{display:flex;align-items:center;gap:12px;padding:18px 20px;border-bottom:1px solid #ffffff0c}.diagHead h2{margin:0;font-size:17px}.diagHead p{margin:4px 0 0;color:#858c9e;font-size:10px}.diagClose{margin-left:auto;width:36px;height:36px;border-radius:10px;background:#ffffff0b;color:#ccd1dc;font-size:18px}
.diagTools{display:flex;gap:8px;padding:12px 16px;border-bottom:1px solid #ffffff0c}.diagTools button{height:40px;padding:0 14px;border-radius:10px;background:#171a25;border:1px solid #ffffff0d;color:#d7dae4;font-size:11px;font-weight:750}.diagTools .primary{background:linear-gradient(135deg,var(--accent),var(--accent2));border-color:#857bff}
.diagSummary{display:flex;gap:8px;flex-wrap:wrap;padding:12px 16px}.diagPill{padding:8px 11px;border-radius:10px;background:#11141c;border:1px solid #ffffff0b;color:#9da4b5;font-size:10px}.diagPill b{color:#fff;margin-right:4px}
.diagList{padding:0 16px 16px;overflow:auto}.diagEmpty{padding:55px 20px;text-align:center;color:#858c9e;font-size:12px;line-height:1.6}
.diagPeer{padding:14px;margin-top:10px;border:1px solid #ffffff0d;background:#10131b;border-radius:15px}.diagPeerTop{display:flex;align-items:center;gap:10px}.diagDot{width:9px;height:9px;border-radius:50%;background:#777;box-shadow:0 0 12px #7778;flex:none}.diagPeer.ok .diagDot{background:var(--good);box-shadow:0 0 14px #55dc91aa}.diagPeer.bad .diagDot{background:var(--danger);box-shadow:0 0 14px #ff667aaa}.diagPeer.warn .diagDot{background:#f1c75b;box-shadow:0 0 14px #f1c75b88}.diagPeerName{font-size:12px;font-weight:800;flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis}.diagPeerId{font-family:monospace;color:#747c8f;font-size:9px;overflow:hidden;text-overflow:ellipsis;max-width:42%}
.diagStatus{margin:9px 0;color:#8f96a8;font-size:10px;line-height:1.5}.diagChecks{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.diagCheck{padding:9px 10px;border-radius:10px;background:#0b0e15;border:1px solid #ffffff08;color:#8e96a8;font-size:10px}.diagCheck b{display:block;color:#e8eaf0;font-size:10px;margin-bottom:3px}.diagPeerActions{display:flex;justify-content:flex-end;margin-top:10px}.diagFix{height:36px;padding:0 13px;border-radius:9px;background:#261a20;border:1px solid #633040;color:#ffb1bd;font-size:10px;font-weight:800}.diagFix:disabled{opacity:.45;cursor:not-allowed}
@media(max-width:600px){.diagCard{border-radius:19px}.diagHead{padding:14px}.diagTools,.diagSummary,.diagList{padding-left:11px;padding-right:11px}.diagChecks{grid-template-columns:1fr}.diagPeerId{max-width:35%}}
`;document.head.appendChild(s)}
function create(){if(modal)return;addStyles();modal=document.createElement("div");modal.className="diagModal hidden";modal.innerHTML='<div class="diagCard"><div class="diagHead"><div><h2>Peer Connections</h2><p>Live P2P connection diagnostics. Tests whether data can travel both ways.</p></div><button class="diagClose" type="button">×</button></div><div class="diagTools"><button class="primary" type="button" id="diagTestAll">Test all connections</button><button type="button" id="diagRefresh">Refresh</button></div><div class="diagSummary" id="diagSummary"></div><div class="diagList" id="diagList"></div></div></div>';document.body.appendChild(modal);list=modal.querySelector("#diagList");summary=modal.querySelector("#diagSummary");modal.querySelector(".diagClose").onclick=close;modal.onclick=e=>{if(e.target===modal)close()};modal.querySelector("#diagTestAll").onclick=()=>testAll();modal.querySelector("#diagRefresh").onclick=render}
function close(){if(modal)modal.classList.add("hidden");clearInterval(autoTimer);autoTimer=null}
function open(){create();modal.classList.remove("hidden");render();clearInterval(autoTimer);autoTimer=setInterval(render,1500)}
function peerEntries(){const out=[];if(typeof connections==="undefined")return out;for(const [id,c] of connections)out.push({id,c});return out}
function esc(v){return String(v||"").replace(/[&<>"]/g,x=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[x]))}
function stateFor(c){if(!c)return"missing";if(c.open)return"connected";if(c.open===false)return"closed";return"connecting"}
function render(){if(!list)return;const peers=peerEntries();const good=peers.filter(x=>x.c&&x.c.open).length;const bad=peers.length-good;summary.innerHTML='<div class="diagPill"><b>'+peers.length+'</b> peers</div><div class="diagPill"><b>'+good+'</b> connected</div><div class="diagPill"><b>'+bad+'</b> not ready</div>';if(!peers.length){list.innerHTML='<div class="diagEmpty">No peer-to-peer connections are currently present.<br>Open another browser/device in the same chat to create a connection.</div>';return}list.innerHTML="";for(const p of peers){const key=p.id;const result=p.result;const cls=result?(result.status==="ok"?"ok":result.status==="bad"?"bad":"warn"):(p.c&&p.c.open?"warn":"bad");const el=document.createElement("div");el.className="diagPeer "+cls;el.innerHTML='<div class="diagPeerTop"><span class="diagDot"></span><div class="diagPeerName">Peer</div><div class="diagPeerId">'+esc(key)+'</div></div><div class="diagStatus">'+esc(result?.message||stateFor(p.c))+'</div><div class="diagChecks"><div class="diagCheck"><b>Send to peer</b>'+esc(result?.out===true?"Working":result?.out===false?"Failed":"Not tested")+'</div><div class="diagCheck"><b>Peer sends to you</b>'+esc(result?.in===true?"Working":result?.in===false?"Failed":"Not tested")+'</div></div><div class="diagPeerActions"><button class="diagFix" type="button" '+((p.c&&p.c.open)||result?"":"disabled")+' data-peer="'+esc(key)+'">Fix connection</button></div>';el.querySelector(".diagFix").onclick=()=>fixPeer(key);list.appendChild(el)}}
function waitFor(id,testId,timeout=3500){return new Promise(resolve=>{const key=testId+":"+id;const timer=setTimeout(()=>{pending.delete(key);resolve(false)},timeout);pending.set(key,{resolve,timer})})}
function finish(id,testId,kind){const p=pending.get(testId+":"+id);if(!p)return;clearTimeout(p.timer);pending.delete(testId+":"+id);p.resolve(true)}
function installHandlers(c){if(!c||c.__diagHandlers)return;c.__diagHandlers=true;c.on("data",d=>{if(!d||!d.type)return;if(d.type==="diag-out"){try{c.send({type:"diag-out-ack",testId:d.testId})}catch(e){};return}if(d.type==="diag-in-request"){try{c.send({type:"diag-in",testId:d.testId})}catch(e){};return}if(d.type==="diag-in"){try{c.send({type:"diag-in-ack",testId:d.testId})}catch(e){};return}if(d.type==="diag-out-ack")finish(c.peer,d.testId,"out");if(d.type==="diag-in-ack")finish(c.peer,d.testId,"in")})}
async function testPeer(id,c){if(!c||!c.open){return{status:"bad",out:false,in:false,message:"Connection is not open. It cannot send or receive data."}}installHandlers(c);const a="o-"+Date.now()+"-"+Math.random().toString(36).slice(2),b="i-"+Date.now()+"-"+Math.random().toString(36).slice(2);let out=false,incoming=false;try{c.send({type:"diag-out",testId:a})}catch(e){}out=await waitFor(id,a);try{c.send({type:"diag-in-request",testId:b})}catch(e){}incoming=await waitFor(id,b);return{status:out&&incoming?"ok":out||incoming?"warn":"bad",out,in:incoming,message:out&&incoming?"Fully working: both directions confirmed.":out?"Outgoing works, but the return/incoming test failed.":incoming?"Incoming works, but outgoing acknowledgement failed.":"Both directional tests failed."}}
function attachIncomingPatch(){if(typeof attach!=="function"||attach.__diagPatched)return;const original=attach;const wrapped=function(c){const before=c&&c.on;const result=original(c);if(c){installHandlers(c)}return result};attach=wrapped;attach.__diagPatched=true}
async function testAll(){const peers=peerEntries().filter(x=>x.c);for(const p of peers){p.result=await testPeer(p.id,p.c);render()}}
async function fixPeer(id){const c=connections&&connections.get(id);if(c){try{c.close()}catch(e){}connections.delete(id)}render();toast("Reconnecting to peer…");setTimeout(()=>{if(typeof peer!=="undefined"&&peer&&peer.open){try{if(typeof connectTo==="function")connectTo(id);else{const nc=peer.connect(id,{reliable:true});if(typeof attach==="function")attach(nc)}}catch(e){}}render()},250);setTimeout(()=>{const c2=connections&&connections.get(id);if(c2){testPeer(id,c2).then(r=>{const p=peerEntries().find(x=>x.id===id);if(p)p.result=r;render()})}},1400)}
function patchAttach(){if(typeof attach!=="function"||attach.__diagPatched)return;const original=attach;const wrapped=function(c){const result=original(c);if(c){setTimeout(()=>installHandlers(c),0)}return result};wrapped.__diagPatched=true;attach=wrapped}
function boot(){create();const top=document.querySelector(".topActions");if(!top||document.getElementById("connectionsBtn"))return;const b=document.createElement("button");b.id="connectionsBtn";b.type="button";b.textContent="Peer Connections";b.onclick=open;top.insertBefore(b,top.firstChild);patchAttach();for(const p of peerEntries())installHandlers(p.c)}
const oldOnLoad=window.onload;window.onload=()=>{if(oldOnLoad)oldOnLoad();boot()};setTimeout(boot,0);setTimeout(boot,500);setTimeout(boot,1500);
window.addEventListener("beforeunload",()=>{for(const p of pending.values())clearTimeout(p.timer)});
})();